# Generated by Django 5.1.2 on 2024-10-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mame',
            new_name='name',
        ),
    ]
